<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <AssemblyName>NetLoader</AssemblyName>
    <RootNamespace>NetLoader</RootNamespace>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <NoWarn>SYSLIB0014</NoWarn>
  </PropertyGroup>
</Project>
